version: '3.8'

networks:
  crypto-bot-dev-network:
    driver: bridge

services:
  python-analysis:
    build: ./python-service
    container_name: crypto-bot-python-analysis-dev
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    volumes:
      - ./python-service:/app
    command: flask run --host=0.0.0.0 --port=8000 --debug
    networks:
      - crypto-bot-dev-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  crypto-bot:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: crypto-bot-main-dev
    ports:
      - "3000:3000"
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PYTHON_SERVICE_URL=http://python-analysis:8000
    restart: unless-stopped
    depends_on:
      python-analysis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - ./bot-config.json:/app/bot-config.json
    networks:
      - crypto-bot-dev-network
    stdin_open: true
    tty: true
