version: '3.8'

services:
  python-analysis:
    build: ./python-service
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./python-service:/app
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout 120 app:app
