// Полный список всех бирж из ccxt (106 бирж)
const allExchanges = [
    'alpaca', 'apex', 'ascendex', 'bequant', 'bigone', 'binance', 'binancecoinm', 'binanceus', 'binanceusdm', 'bingx',
    'bit2c', 'bitbank', 'bitbns', 'bitfinex', 'bitflyer', 'bitget', 'bithumb', 'bitmart', 'bitmex', 'bitopro',
    'bitrue', 'bitso', 'bitstamp', 'bitteam', 'bittrade', 'bitvavo', 'blockchaincom', 'blofin', 'btcalpha', 'btcbox',
    'btcmarkets', 'btcturk', 'bybit', 'cex', 'coinbase', 'coinbaseadvanced', 'coinbaseexchange', 'coinbaseinternational', 'coincatch', 'coincheck',
    'coinex', 'coinlist', 'coinmate', 'coinmetro', 'coinone', 'coinsph', 'coinspot', 'cryptocom', 'cryptomus', 'defx',
    'delta', 'deribit', 'derive', 'digifinex', 'ellipx', 'exmo', 'fmfwio', 'gate', 'gateio', 'gemini',
    'hashkey', 'hitbtc', 'hollaex', 'htx', 'huobi', 'hyperliquid', 'independentreserve', 'indodax', 'kraken', 'krakenfutures',
    'kucoin', 'kucoinfutures', 'latoken', 'lbank', 'luno', 'mercado', 'mexc', 'modetrade', 'myokx', 'ndax',
    'novadax', 'oceanex', 'okcoin', 'okx', 'okxus', 'onetrading', 'oxfun', 'p2b', 'paradex', 'paymium',
    'phemex', 'poloniex', 'probit', 'timex', 'tokocrypto', 'tradeogre', 'upbit', 'vertex', 'wavesexchange', 'whitebit',
    'woo', 'woofipro', 'xt', 'yobit', 'zaif', 'zonda'
];

// Категоризация бирж для удобства пользователей
const exchangeCategories = {
    top: ['binance', 'bybit', 'okx', 'coinbase', 'kraken', 'kucoin', 'bitfinex', 'huobi', 'gate', 'mexc'],
    derivatives: ['bitmex', 'bybit', 'binanceusdm', 'binancecoinm', 'krakenfutures', 'kucoinfutures', 'phemex', 'deribit'],
    regional: ['binanceus', 'coinbaseadvanced', 'gemini', 'btcmarkets', 'bitflyer', 'upbit', 'bithumb', 'coinone'],
    altcoins: ['gate', 'mexc', 'bitget', 'bitmart', 'lbank', 'xt', 'probit', 'latoken'],
    defi: ['coinex', 'pancakeswap', 'dydx', 'hyperliquid'],
    all: allExchanges
};

// Описания бирж
const exchangeDescriptions = {
    'alpaca': 'Alpaca - Американская биржа с алгоритмической торговлей',
    'apex': 'ApeX - Децентрализованная биржа деривативов',
    'ascendex': 'AscendEX - Глобальная цифровая биржа активов',
    'bequant': 'Bequant - Институциональная торговая платформа',
    'bigone': 'BigONE - Международная цифровая биржа активов',
    'binance': 'Binance - Крупнейшая криптовалютная биржа в мире',
    'binancecoinm': 'Binance COIN-M - Фьючерсы с монетной маржей',
    'binanceus': 'Binance US - Американское подразделение Binance',
    'binanceusdm': 'Binance USD-M - Фьючерсы с долларовой маржей',
    'bingx': 'BingX - Биржа с социальным трейдингом',
    'bit2c': 'Bit2C - Израильская криптовалютная биржа',
    'bitbank': 'bitbank - Японская криптовалютная биржа',
    'bitbns': 'BitBNS - Индийская криптовалютная биржа',
    'bitfinex': 'Bitfinex - Профессиональная торговая платформа',
    'bitflyer': 'bitFlyer - Крупнейшая биржа в Японии',
    'bitget': 'Bitget - Биржа с копи-трейдингом и фьючерсами',
    'bithumb': 'Bithumb - Южнокорейская криптовалютная биржа',
    'bitmart': 'BitMart - Глобальная цифровая биржа активов',
    'bitmex': 'BitMEX - Биржа деривативов и фьючерсов',
    'bitopro': 'BitoPro - Тайваньская криптовалютная биржа',
    'bitrue': 'Bitrue - Глобальная криптовалютная биржа',
    'bitso': 'Bitso - Мексиканская криптовалютная биржа',
    'bitstamp': 'Bitstamp - Европейская криптовалютная биржа',
    'bitteam': 'BitTeam - Биржа с командной торговлей',
    'bittrade': 'BitTrade - Японская криптовалютная биржа',
    'bitvavo': 'Bitvavo - Европейская криптовалютная биржа',
    'blockchaincom': 'Blockchain.com - Популярный кошелек и биржа',
    'blofin': 'Blofin - Профессиональная торговая платформа',
    'btcalpha': 'BTC-Alpha - Международная криптовалютная биржа',
    'btcbox': 'BTCBOX - Японская биржа биткоинов',
    'btcmarkets': 'BTC Markets - Австралийская криптовалютная биржа',
    'btcturk': 'BTCTurk - Турецкая криптовалютная биржа',
    'bybit': 'Bybit - Популярная биржа деривативов',
    'cex': 'CEX.IO - Мультифункциональная криптовалютная платформа',
    'coinbase': 'Coinbase - Американская публичная криптобиржа',
    'coinbaseadvanced': 'Coinbase Advanced - Продвинутая торговля',
    'coinbaseexchange': 'Coinbase Exchange - Профессиональная платформа',
    'coinbaseinternational': 'Coinbase International - Международное подразделение',
    'coincatch': 'CoinCatch - Деривативная торговая платформа',
    'coincheck': 'Coincheck - Японская криптовалютная биржа',
    'coinex': 'CoinEx - Глобальная цифровая биржа валют',
    'coinlist': 'CoinList - Платформа для токенизированных активов',
    'coinmate': 'CoinMate - Европейская криптовалютная биржа',
    'coinmetro': 'CoinMetro - Эстонская криптовалютная биржа',
    'coinone': 'CoinOne - Южнокорейская криптовалютная биржа',
    'coinsph': 'Coins.ph - Филиппинская криптовалютная биржа',
    'coinspot': 'CoinSpot - Австралийская криптовалютная биржа',
    'cryptocom': 'Crypto.com - Мобильная криптовалютная платформа',
    'cryptomus': 'Cryptomus - Криптовалютная платформа для платежей',
    'defx': 'DEFX - Биржа децентрализованных финансов',
    'delta': 'Delta - Биржа деривативов',
    'deribit': 'Deribit - Европейская биржа деривативов',
    'derive': 'Derive - DEX биржа',
    'digifinex': 'DigiFinex - Сингапурская цифровая биржа активов',
    'ellipx': 'EllipX - Биржа для алгоритмической торговли',
    'exmo': 'EXMO - Европейская криптовалютная биржа',
    'fmfwio': 'FMFW.io - Институциональная торговая платформа',
    'gate': 'Gate.io - Международная криптовалютная биржа',
    'gateio': 'Gate.io - Альтернативное название Gate.io',
    'gemini': 'Gemini - Американская регулируемая биржа',
    'hashkey': 'HashKey - Азиатская институциональная биржа',
    'hitbtc': 'HitBTC - Европейская криптовалютная биржа',
    'hollaex': 'HollaEx - Белая метка биржевого программного обеспечения',
    'htx': 'HTX - Глобальная криптовалютная биржа',
    'huobi': 'Huobi - Международная цифровая биржа активов',
    'hyperliquid': 'Hyperliquid - L1 блокчейн для деривативов',
    'independentreserve': 'Independent Reserve - Австралийская/Новозеландская биржа',
    'indodax': 'Indodax - Индонезийская криптовалютная биржа',
    'kraken': 'Kraken - Американская криптовалютная биржа',
    'krakenfutures': 'Kraken Futures - Деривативная платформа Kraken',
    'kucoin': 'KuCoin - "Народная биржа"',
    'kucoinfutures': 'KuCoin Futures - Фьючерсная платформа KuCoin',
    'latoken': 'LATOKEN - Мультиактивная торговая платформа',
    'lbank': 'LBank - Международная криптовалютная биржа',
    'luno': 'Luno - Биржа в Африке и Юго-Восточной Азии',
    'mercado': 'Mercado Bitcoin - Бразильская криптовалютная биржа',
    'mexc': 'MEXC - Глобальная криптовалютная биржа',
    'modetrade': 'Mode Trade - Современная торговая платформа',
    'myokx': 'MyOKX - Персонализированная платформа OKX',
    'ndax': 'NDAX - Канадская криптовалютная биржа',
    'novadax': 'NovaDAX - Бразильская криптовалютная биржа',
    'oceanex': 'OceanEx - Криптовалютная биржа VeChain',
    'okcoin': 'OKCoin - Глобальная криптовалютная биржа',
    'okx': 'OKX - Ведущая криптовалютная биржа и Web3 компания',
    'okxus': 'OKX US - Американское подразделение OKX',
    'onetrading': 'One Trading - Европейская криптовалютная биржа',
    'oxfun': 'OXFun - Биржа деривативов',
    'p2b': 'P2B - Международная криптовалютная биржа',
    'paradex': 'Paradex - Децентрализованная биржа',
    'paymium': 'Paymium - Французская биржа биткоинов',
    'phemex': 'Phemex - Биржа криптовалютных деривативов',
    'poloniex': 'Poloniex - Американская криптовалютная биржа',
    'probit': 'ProBit - Глобальная криптовалютная биржа',
    'timex': 'TimeX - Гибридная децентрализованная биржа',
    'tokocrypto': 'Tokocrypto - Индонезийская криптовалютная биржа',
    'tradeogre': 'TradeOgre - Биржа для альткоинов',
    'upbit': 'Upbit - Южнокорейская криптовалютная биржа',
    'vertex': 'Vertex - Децентрализованная биржа деривативов',
    'wavesexchange': 'Waves.Exchange - Децентрализованная биржа',
    'whitebit': 'WhiteBIT - Европейская криптовалютная биржа',
    'woo': 'WOO - Биржа с глубокой ликвидностью',
    'woofipro': 'WooFi Pro - Профессиональная торговая платформа',
    'xt': 'XT.COM - Глобальная криптовалютная торговая платформа',
    'yobit': 'YoBit - Российская криптовалютная биржа',
    'zaif': 'Zaif - Японская криптовалютная биржа',
    'zonda': 'Zonda - Европейская криптовалютная биржа'
};

console.log('Создана полная конфигурация для всех 106 бирж ccxt');
